version: '3'

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/static/
      - media:/app/media/

  frontend:
    build: ./frontend/
    volumes:
      - frontend_build:/usr/share/nginx/html/

  gateway:
    build: ./nginx/
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/media/
      - frontend_build:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media:
  frontend_build: 