services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_USERNAME}/kittygram_backend3
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - static:/static/static/
      - media:/app/media

  frontend:
    image: ${DOCKER_USERNAME}/kittygram_frontend3
    build: 
      context: ./frontend/
      dockerfile: Dockerfile

  gateway:
    image: ${DOCKER_USERNAME}/kittygram_gateway3
    build: ./nginx/
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - static:/static/static/
      - media:/app/media
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media:
  frontend_build: 